/* Auto-generated by genmsg_cpp for file /home/jxsun/ROS_NEW_NODE/quadrotorTestControl/msg/Point3D.msg */
#ifndef QUADROTORTESTCONTROL_MESSAGE_POINT3D_H
#define QUADROTORTESTCONTROL_MESSAGE_POINT3D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace quadrotorTestControl
{
template <class ContainerAllocator>
struct Point3D_ {
  typedef Point3D_<ContainerAllocator> Type;

  Point3D_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  Point3D_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;


  typedef boost::shared_ptr< ::quadrotorTestControl::Point3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotorTestControl::Point3D_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Point3D
typedef  ::quadrotorTestControl::Point3D_<std::allocator<void> > Point3D;

typedef boost::shared_ptr< ::quadrotorTestControl::Point3D> Point3DPtr;
typedef boost::shared_ptr< ::quadrotorTestControl::Point3D const> Point3DConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotorTestControl::Point3D_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotorTestControl::Point3D_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotorTestControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::Point3D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::Point3D_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotorTestControl::Point3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const  ::quadrotorTestControl::Point3D_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotorTestControl::Point3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotorTestControl/Point3D";
  }

  static const char* value(const  ::quadrotorTestControl::Point3D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotorTestControl::Point3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
\n\
";
  }

  static const char* value(const  ::quadrotorTestControl::Point3D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quadrotorTestControl::Point3D_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotorTestControl::Point3D_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Point3D_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotorTestControl::Point3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotorTestControl::Point3D_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTORTESTCONTROL_MESSAGE_POINT3D_H

