/* Auto-generated by genmsg_cpp for file /home/cooplab/jianxin/rosbuild_ws/sandbox/quadrotorTestControl/srv/getTargetPosition.srv */
#ifndef QUADROTORTESTCONTROL_SERVICE_GETTARGETPOSITION_H
#define QUADROTORTESTCONTROL_SERVICE_GETTARGETPOSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace quadrotorTestControl
{
template <class ContainerAllocator>
struct getTargetPositionRequest_ {
  typedef getTargetPositionRequest_<ContainerAllocator> Type;

  getTargetPositionRequest_()
  {
  }

  getTargetPositionRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct getTargetPositionRequest
typedef  ::quadrotorTestControl::getTargetPositionRequest_<std::allocator<void> > getTargetPositionRequest;

typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionRequest> getTargetPositionRequestPtr;
typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionRequest const> getTargetPositionRequestConstPtr;



template <class ContainerAllocator>
struct getTargetPositionResponse_ {
  typedef getTargetPositionResponse_<ContainerAllocator> Type;

  getTargetPositionResponse_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  getTargetPositionResponse_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;


  typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct getTargetPositionResponse
typedef  ::quadrotorTestControl::getTargetPositionResponse_<std::allocator<void> > getTargetPositionResponse;

typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionResponse> getTargetPositionResponsePtr;
typedef boost::shared_ptr< ::quadrotorTestControl::getTargetPositionResponse const> getTargetPositionResponseConstPtr;


struct getTargetPosition
{

typedef getTargetPositionRequest Request;
typedef getTargetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct getTargetPosition
} // namespace quadrotorTestControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotorTestControl/getTargetPositionRequest";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotorTestControl/getTargetPositionResponse";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
\n\
\n\
";
  }

  static const char* value(const  ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct getTargetPositionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct getTargetPositionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<quadrotorTestControl::getTargetPosition> {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const quadrotorTestControl::getTargetPosition&) { return value(); } 
};

template<>
struct DataType<quadrotorTestControl::getTargetPosition> {
  static const char* value() 
  {
    return "quadrotorTestControl/getTargetPosition";
  }

  static const char* value(const quadrotorTestControl::getTargetPosition&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotorTestControl/getTargetPosition";
  }

  static const char* value(const quadrotorTestControl::getTargetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotorTestControl/getTargetPosition";
  }

  static const char* value(const quadrotorTestControl::getTargetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // QUADROTORTESTCONTROL_SERVICE_GETTARGETPOSITION_H

