(cl:defpackage quadrotorTestControl-srv
  (:use )
  (:export
   "GETTARGETVELOCITY"
   "<GETTARGETVELOCITY-REQUEST>"
   "GETTARGETVELOCITY-REQUEST"
   "<GETTARGETVELOCITY-RESPONSE>"
   "GETTARGETVELOCITY-RESPONSE"
   "GETTARGETPOSITION"
   "<GETTARGETPOSITION-REQUEST>"
   "GETTARGETPOSITION-REQUEST"
   "<GETTARGETPOSITION-RESPONSE>"
   "GETTARGETPOSITION-RESPONSE"
  ))

